# CMake generated Testfile for 
# Source directory: /home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests
# Build directory: /home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestSerializationNode "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializationNode")
set_tests_properties(TestSerializationNode PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeAndersenThermostat "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeAndersenThermostat")
set_tests_properties(TestSerializeAndersenThermostat PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCMAPTorsion "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCMAPTorsion")
set_tests_properties(TestSerializeCMAPTorsion PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCMMotionRemover "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCMMotionRemover")
set_tests_properties(TestSerializeCMMotionRemover PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomAngleForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomAngleForce")
set_tests_properties(TestSerializeCustomAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomBondForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomBondForce")
set_tests_properties(TestSerializeCustomBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomCVForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomCVForce")
set_tests_properties(TestSerializeCustomCVForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomCentroidBondForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomCentroidBondForce")
set_tests_properties(TestSerializeCustomCentroidBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomCompoundBondForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomCompoundBondForce")
set_tests_properties(TestSerializeCustomCompoundBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomExternalForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomExternalForce")
set_tests_properties(TestSerializeCustomExternalForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomGBForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomGBForce")
set_tests_properties(TestSerializeCustomGBForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomHbondForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomHbondForce")
set_tests_properties(TestSerializeCustomHbondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomManyParticleForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomManyParticleForce")
set_tests_properties(TestSerializeCustomManyParticleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomNonbondedForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomNonbondedForce")
set_tests_properties(TestSerializeCustomNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomTorsionForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeCustomTorsionForce")
set_tests_properties(TestSerializeCustomTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeGBSAOBCForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeGBSAOBCForce")
set_tests_properties(TestSerializeGBSAOBCForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeGayBerneForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeGayBerneForce")
set_tests_properties(TestSerializeGayBerneForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeHarmonicAngleForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeHarmonicAngleForce")
set_tests_properties(TestSerializeHarmonicAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeHarmonicBondForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeHarmonicBondForce")
set_tests_properties(TestSerializeHarmonicBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeIntegrator "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeIntegrator")
set_tests_properties(TestSerializeIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeMonteCarloAnisotropicBarostat "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeMonteCarloAnisotropicBarostat")
set_tests_properties(TestSerializeMonteCarloAnisotropicBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeMonteCarloBarostat "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeMonteCarloBarostat")
set_tests_properties(TestSerializeMonteCarloBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeMonteCarloMembraneBarostat "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeMonteCarloMembraneBarostat")
set_tests_properties(TestSerializeMonteCarloMembraneBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeNonbondedForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeNonbondedForce")
set_tests_properties(TestSerializeNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeNoseHooverIntegrator "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeNoseHooverIntegrator")
set_tests_properties(TestSerializeNoseHooverIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializePeriodicTorsionForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializePeriodicTorsionForce")
set_tests_properties(TestSerializePeriodicTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeRBTorsionForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeRBTorsionForce")
set_tests_properties(TestSerializeRBTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeRMSDForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeRMSDForce")
set_tests_properties(TestSerializeRMSDForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeState "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeState")
set_tests_properties(TestSerializeState PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeSystem "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeSystem")
set_tests_properties(TestSerializeSystem PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeTabulatedFunctions "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestSerializeTabulatedFunctions")
set_tests_properties(TestSerializeTabulatedFunctions PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/serialization/tests/CMakeLists.txt;0;")
