CONFIG_RUN_ALPHAFOLD = {
    "fasta_paths": ["/home/taylorjones/Documents/alphafold_fastas/forAlican11_8_recycles.fasta"],
    "output_dir": "/home/taylorjones/Documents/alphafold_output", 
    "model_names": ['model_5'], 
    "data_dir": "/media/taylorjones/bigboi/alphafold_data/params2",
    "jackhmmer_binary_path": "/home/taylorjones/software/taylorsScripts/externalExecutables/linux_x86/jackhmmer", 
    "hhblits_binary_path": "/usr/local/bin/hhblits",
    "hhsearch_binary_path": "/usr/local/bin/hhsearch",
    "kalign_binary_path": "/usr/bin/kalign",
    "uniref90_database_path": "/media/taylorjones/8Tb1/alphafold_data/uniref90/uniref90.fasta",
    "mgnify_database_path": "/media/taylorjones/8Tb1/alphafold_data/mgnify/mgy_clusters_2018_12.fa",
    "small_bfd_database_path": "/media/taylorjones/bigboi/alphafold_data/bfd_small/bfd-first_non_consensus_sequences.fasta",
    #"uniclust30_database_path": "/media/taylorjones/8Tb1/alphafold_data/uniclust30/uniclust30_2018_08/uniclust30_2018_08",
    "pdb70_database_path": "/media/taylorjones/8Tb1/alphafold_data/pdb70/pdb70",
    "template_mmcif_dir": "/media/taylorjones/8Tb1/alphafold_data/pdb_mmcif/mmcif_files",
    "max_template_date": "2020-05-14",
    "obsolete_pdbs_path": "/media/taylorjones/8Tb1/alphafold_data/pdb_mmcif/obsolete.dat", 
    "db_preset": "reduced_dbs", 
    "benchmark": False,
    "activations_output_path": "/media/taylorjones/8Tb1/alphafold_activations/",
    "model_preset": "multimer",
    "pdb_seqres_database_path":"/media/taylorjones/bigboi/alphafold_data/uniprot/pdb_seqres/pdb_seqres.txt",
    "uniprot_database_path": "/media/taylorjones/bigboi/alphafold_data/uniprot/uniprot/uniprot.fasta",
    "random_seed": None
}

