# CMake generated Testfile for 
# Source directory: /home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests
# Build directory: /home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestCpuCheckpoints "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuCheckpoints" "single")
set_tests_properties(TestCpuCheckpoints PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCompoundIntegrator "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuCompoundIntegrator" "single")
set_tests_properties(TestCpuCompoundIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCustomGBForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuCustomGBForce" "single")
set_tests_properties(TestCpuCustomGBForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCustomManyParticleForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuCustomManyParticleForce" "single")
set_tests_properties(TestCpuCustomManyParticleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCustomNonbondedForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuCustomNonbondedForce" "single")
set_tests_properties(TestCpuCustomNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuDispersionPME "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuDispersionPME" "single")
set_tests_properties(TestCpuDispersionPME PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuEwald "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuEwald" "single")
set_tests_properties(TestCpuEwald PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuGBSAOBCForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuGBSAOBCForce" "single")
set_tests_properties(TestCpuGBSAOBCForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuGayBerneForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuGayBerneForce" "single")
set_tests_properties(TestCpuGayBerneForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuHarmonicAngleForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuHarmonicAngleForce" "single")
set_tests_properties(TestCpuHarmonicAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuLangevinIntegrator "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuLangevinIntegrator" "single")
set_tests_properties(TestCpuLangevinIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuLangevinMiddleIntegrator "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuLangevinMiddleIntegrator" "single")
set_tests_properties(TestCpuLangevinMiddleIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuNeighborList "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuNeighborList" "single")
set_tests_properties(TestCpuNeighborList PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuNonbondedForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuNonbondedForce" "single")
set_tests_properties(TestCpuNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuPeriodicTorsionForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuPeriodicTorsionForce" "single")
set_tests_properties(TestCpuPeriodicTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuRBTorsionForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuRBTorsionForce" "single")
set_tests_properties(TestCpuRBTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuSettle "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestCpuSettle" "single")
set_tests_properties(TestCpuSettle PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;27;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/platforms/cpu/tests/CMakeLists.txt;0;")
