#!/bin/bash
./run_alphafold.py --fasta_names 2.A.1.1.124.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.1.124.fasta_other  --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.1.13.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.1.13.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.1.24.fasta --model_names model_5 --overwrite --num_structures 10  --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.1.24.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.1.28.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.1.28.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.1.3.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.1.3.fasta_other  --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.1.37.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.1.37.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.1.91.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.1.91.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.11.1.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.11.1.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.13.5.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.13.5.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.14.16.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.14.16.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.2.15.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.2.15.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.2.19.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.2.19.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.2.44.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.2.44.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.2.5.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.2.5.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.2.60.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.2.60.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.2.9.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.2.9.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.22.6.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.22.6.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.4.3.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.4.3.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.5.1.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.5.1.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.6.4.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.6.4.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.7.1.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.7.1.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.8.1.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.8.1.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.8.10.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.8.10.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.1.9.10.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.1.9.10.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.17.1.2.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.17.1.2.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.17.1.4.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.17.1.4.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.17.1.6.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.17.1.6.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.17.1.7.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.17.1.7.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.17.3.1.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.17.3.1.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.17.4.7.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.17.4.7.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.17.4.8.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.17.4.8.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.57.1.1.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.57.1.1.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.57.2.4.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.57.2.4.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.60.1.19.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.60.1.19.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.100.1.4.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.100.1.4.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 2.A.100.2.1.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 2.A.100.2.1.fasta_other --use_precomputed_msas 
./run_alphafold.py --fasta_names 5.B.2.1.3.fasta --model_names model_5 --overwrite --num_structures 10 --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax --job_name 5.B.2.1.3.fasta_other --use_precomputed_msas 



# --num_recycle 0 --max_extra_msa 16 --db_preset reduced_dbs --norun_relax
