#!/bin/bash

./run_alphafold.py --use_precomputed_msas --fasta_names 1A0R_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1A6E_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1AJ7_H.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1AW1_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1B6H_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1CG0_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1CZ2_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1DFJ_I.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1E1R_F.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1E5Q_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1EEJ_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1EIO_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1EL1_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1EQM_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1EVL_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1EX7_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1FIL_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1FQO_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1G51_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1GQT_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1GY9_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1H9G_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1HSH_D.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1ID8_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1IGP_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1JFK_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1JG6_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1JKN_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1JTB_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1K0B_C.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1K70_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1KRX_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1LAH_E.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1MO8_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1MX8_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1NJF_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1O03_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1O1V_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1P7M_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1PUN_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1Q0Q_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1Q95_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1QFE_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1QJ8_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1RF4_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1RGH_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1ROE_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1RPJ_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1RRO_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1RTP_1.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1RZM_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1SSP_E.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1TJ5_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1TNQ_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1UR6_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1URE_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1UVB_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1VHL_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1WCW_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1WUM_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1XSC_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1XYD_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1Y3N_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1YHO_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1YL7_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1Z17_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 1ZFS_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2AU6_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2B0F_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2BEM_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2CG6_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2DRI_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2ECK_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2GKE_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2HLT_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2JU8_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2K0G_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2K8R_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2KID_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2L51_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2LKD_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2LKK_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2OZW_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2RS9_B.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2VBT_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 2VCD_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
./run_alphafold.py --use_precomputed_msas --fasta_names 3UC5_A.fasta --overwrite --mgnify_max_hits 50 --uniref_max_hits 500
