# CMake generated Testfile for 
# Source directory: /home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests
# Build directory: /home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestReferenceAmoebaAngleForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaAngleForce")
set_tests_properties(TestReferenceAmoebaAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaBondForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaBondForce")
set_tests_properties(TestReferenceAmoebaBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaExtrapolatedPolarization "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaExtrapolatedPolarization")
set_tests_properties(TestReferenceAmoebaExtrapolatedPolarization PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaGeneralizedKirkwoodForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaGeneralizedKirkwoodForce")
set_tests_properties(TestReferenceAmoebaGeneralizedKirkwoodForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaInPlaneAngleForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaInPlaneAngleForce")
set_tests_properties(TestReferenceAmoebaInPlaneAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaMultipoleForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaMultipoleForce")
set_tests_properties(TestReferenceAmoebaMultipoleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaOutOfPlaneBendForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaOutOfPlaneBendForce")
set_tests_properties(TestReferenceAmoebaOutOfPlaneBendForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaPiTorsionForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaPiTorsionForce")
set_tests_properties(TestReferenceAmoebaPiTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaStretchBendForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaStretchBendForce")
set_tests_properties(TestReferenceAmoebaStretchBendForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaTorsionTorsionForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaTorsionTorsionForce")
set_tests_properties(TestReferenceAmoebaTorsionTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAmoebaVdwForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceAmoebaVdwForce")
set_tests_properties(TestReferenceAmoebaVdwForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceHippoNonbondedForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceHippoNonbondedForce")
set_tests_properties(TestReferenceHippoNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceWcaDispersionForce "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/TestReferenceWcaDispersionForce")
set_tests_properties(TestReferenceWcaDispersionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;16;ADD_TEST;/home/taylorjones/Documents/alphafold/docker/openmm-7.5.1/plugins/amoeba/platforms/reference/tests/CMakeLists.txt;0;")
